### ISSUE TITLE
Bug pada fitur subscribe

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#10]
Fitur email Subscribe bisa diinput selain format email

![Screenshot 2019-10-17 15 27 50](https://user-images.githubusercontent.com/55181810/66991657-b622da00-f0f2-11e9-98da-412b2f4468d4.png)

**Comment by hanaghaliyah** [comment]
Itu bawaan dari templatenya dan belum ku ubah, websiteku tidak ada fitur subcribe
