### ISSUE TITLE
Page select button belum berfungsi

### ISSUE THREAD

**Issue by MadeBy-Ali** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#11]
![1571303277777](https://user-images.githubusercontent.com/49668571/66994983-65ae7b00-f0f8-11e9-94da-e7b321360ee9.jpg)

Pada page "Destinasi Wisata", "Hotel", "Tour Guide", "Transportasi" terdapat page selection button, pada page "Destinasi Wisata" dan "Hotel" page selection button tersebut berkeja sampai page dua dari lima page. Namun di page "Tour Guide" dan "Transportasi" belum ada yang berfungsi

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67359289-156a6980-f58d-11e9-9a4e-b67f7bcd745b.jpg)


sdh mas, tapi baru sampai page 2
