### ISSUE TITLE
Log Out error, mungkin databasenya ada yang salah

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#14]
![image](https://user-images.githubusercontent.com/55182333/67179113-7bc18180-f3ff-11e9-8341-9c12d54ee02c.png)

**Comment by hanaghaliyah** [comment]
Log Out nya udah bisa gan
![Screenshot (16)](https://user-images.githubusercontent.com/26424136/67383221-013c6180-f5b9-11e9-8996-0615aea648cc.png)
