### ISSUE TITLE
Filter Product

### ISSUE THREAD

**Issue by bagasimmanuel** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#15]
![Screenshot from 2019-10-21 22-34-04](https://user-images.githubusercontent.com/55182200/67189394-54c37980-f418-11e9-9ed1-b992f064594d.png)
Filter Product untuk Rating, Nama Kota, dll meskipun sudah di rubah tidak merubah apa apa mungkin bisa menambahkan fitur AJAX

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67762687-9c7d7d00-fa78-11e9-905c-5dfa64934fae.jpg)
![Capture1](https://user-images.githubusercontent.com/50489529/67762688-9d161380-fa78-11e9-83a9-ae3579b8ef4c.JPG)

Sudah tapi untuk sementara hanya hotel untuk yogyakarta saja
