### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#16]
![image](https://user-images.githubusercontent.com/49645946/67190862-ea600880-f41a-11e9-9c20-be7549c0f725.png)

**Comment by hanaghaliyah** [comment]
Done
![Screenshot (15)](https://user-images.githubusercontent.com/26424136/67380999-6726ea00-f5b5-11e9-8186-2a91ef08d4bf.png)
