### ISSUE TITLE
signup error

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#18]
![image](https://user-images.githubusercontent.com/49645946/67191197-6fe3b880-f41b-11e9-963f-3884c4be3026.png)

**Comment by hanaghaliyah** [comment]
udah bisa nih
![Screenshot (14)](https://user-images.githubusercontent.com/26424136/67380740-fd0e4500-f5b4-11e9-974a-9573c99b326b.png)
