### ISSUE TITLE
tombol home salah arah

### ISSUE THREAD

**Issue by donny1412** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#19]
setelah tombol home ditekan dia balik lagi ke sebelum login padahal harusnya tidak perlu login lagi
<img width="960" alt="fanagu1" src="https://user-images.githubusercontent.com/55181699/67264673-f9f05780-f4d5-11e9-97ac-2e188c9216fa.png">

**Comment by hanaghaliyah** [comment]
Sudah diperbaiki gan
[
![Uploading Screenshot (13).png…]()
](url)

**Comment by hanaghaliyah** [comment]
udah gan
![Screenshot (13)](https://user-images.githubusercontent.com/26424136/67380181-267aa100-f5b4-11e9-9163-03c45d31ab71.png)
