### ISSUE TITLE
Star Rating Filter tidak berfungsi

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#20]
mencoba filter dengan bintang 1&2 tapi tidak dapat terfilter dan tetap seperti sebelumnya tidak berubah
![Screenshot (12)](https://user-images.githubusercontent.com/55182134/67266072-805a6880-f4d9-11e9-9705-d8efc021c666.png)

**Comment by agung56** [comment]
Fitur tersebut tidak digunakan diwebsite kami dan akan segera kami hapus
