### ISSUE TITLE
page booknya blm ada

### ISSUE THREAD

**Issue by komangbayu99** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#22]
![Capture](https://user-images.githubusercontent.com/55182023/67835831-955c7a80-fb1d-11e9-8b73-7a827c9a22ff.jpg)

**Comment by Krauszie** [comment]
sdh bang ini bang klo mau ngebook tp blm bsa checkout

![Capture](https://user-images.githubusercontent.com/50489529/67835909-c177fb80-fb1d-11e9-956c-f55f3445287d.jpg)
