### ISSUE TITLE
Tidak bisa kembali ke menu hotel setelah booking kamar

### ISSUE THREAD

**Issue by komangbayu99** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#23]
![Capture1](https://user-images.githubusercontent.com/55182023/67836913-6bf11e00-fb20-11e9-97ff-d35626e2ccbd.JPG)

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67837119-e326b200-fb20-11e9-9fbe-b0bf81ebd2e1.jpg)

sudah broooo
