### ISSUE TITLE
Salah masuk page ketika menekan tombol check out

### ISSUE THREAD

**Issue by komangbayu99** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#24]
![Capture2](https://user-images.githubusercontent.com/55182023/67837535-d8b8e800-fb21-11e9-8fa4-cc0681920101.JPG)

**Comment by Krauszie** [comment]
![Uploading Capture1.JPG…]()

sejatinya memang blm ad tombol checkout bang jdnya klo checkout hrsnya jd page seperti yg d foto dan skrg sdh saya perbaiki

**Comment by Krauszie** [comment]
sejatinya memang blm ad tombol checkout bang jdnya klo checkout hrsnya jd page seperti yg d foto dan skrg sdh saya perbaiki

![Capture](https://user-images.githubusercontent.com/50489529/67837864-9ba12580-fb22-11e9-84de-cb675e146c7e.jpg)
