### ISSUE TITLE
Ketika menekan gambar hotel kembali ke page itu sendiri

### ISSUE THREAD

**Issue by komangbayu99** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#25]
![Capture3](https://user-images.githubusercontent.com/55182023/67838105-297d1080-fb23-11e9-9823-1b0660005f38.JPG)

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67838267-7e208b80-fb23-11e9-95d9-25f3814e3d94.jpg)

itu emg blm d buat pagenya, baru 3 hotel doang yg bsa ngebook jdnya sisanya ke page maintenance dan ini baru saya perbaiki
