### ISSUE TITLE
Link pada Gambar

### ISSUE THREAD

**Issue by Rezaaisyi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#27]
![image](https://user-images.githubusercontent.com/55181853/68219669-f0f49f80-0018-11ea-9e2c-d4dc7c7bce0d.png)
Selamat malam kawan, saya rasa issue ini sudah pernah ada ... saran saja sebaiknya link nya diarahkan ke halaman dengan tulisan "sedang tahap pengembangan". Terima Kasih

**Comment by agung56** [comment]
terima kasih atas saran yang telah diberikan
