### ISSUE TITLE
Log Out belum ke link ke home page

### ISSUE THREAD

**Issue by Bhaskaraa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#3]
saat mencoba menekan button log out, ada terjadi bug dan eror, mungkin belum ke link ke homepage yang ada button loginnya, jadi mungkin bisa dihubungkan ke page yang itu, semangatt!

**Comment by hanaghaliyah** [comment]
sudah ku perbaiki gan
