### ISSUE TITLE
Belum Log In tapi sudah ada tampilan Log Out

### ISSUE THREAD

**Issue by anggadaputra11319** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#4]
Mungkin bisa diedit lagi tombol log out jadi tombol log in
![{8C784BB9-1C09-453C-91AB-B7ED801FAB41} png](https://user-images.githubusercontent.com/47882546/66978142-dfcc0900-f0d2-11e9-8581-7bc8a1ccacbc.jpg)

**Comment by hanaghaliyah** [comment]
udah kuperbaiki gan
