### ISSUE TITLE
Ketika tombol Log Out ditekan maka halaman mengarah ke login.php dan error

### ISSUE THREAD

**Issue by anggadaputra11319** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#5]
ada error pada conn.php line ke9, semangat rek :))
![{9DC268C6-3A60-4DCE-99D7-33E041DC7C11} png](https://user-images.githubusercontent.com/47882546/66978210-346f8400-f0d3-11e9-9f49-df2fdcd88d76.jpg)

**Comment by hanaghaliyah** [comment]
udah bisa gan
![Screenshot (16)](https://user-images.githubusercontent.com/26424136/67382832-5330b780-f5b8-11e9-8b7b-7a2f9f49a3a4.png)
