### ISSUE TITLE
Feature di dalam footer bar belum berfungsi

### ISSUE THREAD

**Issue by MadeBy-Ali** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#6]
Pada page "Destinasi Wisata", "Hotel", "Tour Guide", "Transportasi"  terdapat footer bar yang sama dan semua feature di dalam footer bar tersebut belum ada yang berfungsi

picture dibawah adalah footer bar dari page "destinasi wisata" mewakili 3 page selanjutnya:

![messageImage_1571298743513](https://user-images.githubusercontent.com/49668571/66989825-4a8b3d80-f0ef-11e9-81b5-bb03610a4a52.jpg)

**Comment by hanaghaliyah** [comment]
beberapa feature ada yg dihapus, yang bener seperti gambar dibawah
![Screenshot (17)](https://user-images.githubusercontent.com/26424136/67383035-adca1380-f5b8-11e9-860d-492ef0dcd19b.png)
