### ISSUE TITLE
Slider tidak berfungsi

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#7]
Pada halaman hoteljogja.html?#, Slider tidak mengubah apapun

![Screenshot 2019-10-17 15 14 49](https://user-images.githubusercontent.com/55181810/66990732-f3866800-f0f0-11e9-973d-7ed52c3e0d95.png)

**Comment by hanaghaliyah** [comment]
Itu fitur bawaan dari templatenya dan belum ku ubah, websiteku tidak ku kasih fitur slider
