### ISSUE TITLE
Perbedaan Mata Uang

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#8]
Pada halaman transportasi.html, mata uang berupa dollar,

![Screenshot 2019-10-17 15 20 35](https://user-images.githubusercontent.com/55181810/66991140-afe02e00-f0f1-11e9-8778-05d7bf5bb9ad.png)

Tetapi pada halaman Tour%20Guide.html, mata uang berupa Rupiah

![Screenshot 2019-10-17 15 21 47](https://user-images.githubusercontent.com/55181810/66991228-d900be80-f0f1-11e9-9f32-8d0a9b40963a.png)

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67359088-8eb58c80-f58c-11e9-95b5-2d3a2277f5b1.jpg)


itu blm selesai mas, kami ga pakai transportasi
