### ISSUE TITLE
Invalid input pada page hotel

### ISSUE THREAD

**Issue by MadeBy-Ali** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-fanagu#9]
![123989](https://user-images.githubusercontent.com/49668571/66991752-df436a80-f0f2-11e9-866d-8c540473e16a.jpg)

Pada page hotel terdapat feature pencarian hotel berdasarkan lokasi, tanggal mulai menginap dan tanggal selesai menginap. 

namun input tanggal selesai menginap bisa diisi dengan tanggal sebelum tanggal mulai menginap

contoh: mm/dd/yy
             mulai menginap 10/1/2019
             selesai menginap 8/1/2019

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67359186-cfada100-f58c-11e9-9b3c-4299b86c176f.jpg)

sdh skrg mas, tp baru sampai page 2

**Comment by Krauszie** [comment]
![Capture](https://user-images.githubusercontent.com/50489529/67747085-8d87d200-fa5a-11e9-84fd-fdd476e4ca7a.jpg)

maaf mas ga pake fitur itu, cuma ad fitur search dan itu bekerja untuk yang yogyakarta
